<?php
defined('ABSPATH')||exit;
define('SN_V','6.0.0');define('SN_URI',get_template_directory_uri());

add_action('after_setup_theme',function(){add_theme_support('title-tag');add_theme_support('post-thumbnails');add_theme_support('html5',['search-form','comment-form','comment-list','gallery','caption','style','script']);add_image_size('sn-card',600,400,true);});
add_action('wp_enqueue_scripts',function(){
    wp_enqueue_style('sn-fonts','https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700;800&display=swap',[],null);
    wp_enqueue_style('sn-main',SN_URI.'/assets/css/main.css',['sn-fonts'],SN_V);
    wp_enqueue_script('sn-main',SN_URI.'/assets/js/main.js',[],SN_V,true);
});
add_action('wp_head',function(){echo '<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>';},1);

add_action('wp_ajax_sn_submit_booking','sn_bk');add_action('wp_ajax_nopriv_sn_submit_booking','sn_bk');
function sn_bk(){
    if(!wp_verify_nonce($_POST['sn_nonce']??'','sn_booking'))wp_send_json_error(['message'=>'Session expirée.']);
    if(!empty($_POST['sn_website']))wp_send_json_success();
    $n=sanitize_text_field($_POST['sn_name']??'');$e=sanitize_email($_POST['sn_email']??'');
    $p=sanitize_text_field($_POST['sn_phone']??'');$d=sanitize_text_field($_POST['sn_date']??'');
    if(!$n||!$e||!$p||!$d)wp_send_json_error(['message'=>'Tous les champs sont obligatoires.']);
    if(!is_email($e))wp_send_json_error(['message'=>'Email invalide.']);
    $body="RESERVATION SHAMPOUINEUSE\n".str_repeat('-',30)."\nNom: $n\nEmail: $e\nTel: $p\nDate: $d\nRetrait: Reze\n".str_repeat('-',30)."\n".current_time('d/m/Y H:i');
    $h=['Content-Type: text/plain; charset=UTF-8','Reply-To: '.$n.' <'.$e.'>'];
    wp_mail('shampouineusenantes@gmail.com','Reservation - '.$n,$body,$h)?wp_send_json_success():wp_send_json_error(['message'=>"Erreur d'envoi."]);
}

add_action('wp_head',function(){
    if(!is_front_page()&&!is_page_template('template-homepage.php'))return;
    $lb=['@context'=>'https://schema.org','@type'=>'LocalBusiness','name'=>'Location Shampouineuse Nantes','description'=>'Location shampouineuse Karcher Puzzi 8/1 a Nantes. 25 euros/jour.','url'=>home_url('/'),'email'=>'shampouineusenantes@gmail.com','address'=>['@type'=>'PostalAddress','addressLocality'=>'Reze','postalCode'=>'44400','addressCountry'=>'FR'],'geo'=>['@type'=>'GeoCoordinates','latitude'=>47.1787,'longitude'=>-1.5489],'areaServed'=>[['@type'=>'City','name'=>'Nantes'],['@type'=>'City','name'=>'Reze'],['@type'=>'City','name'=>'Saint-Herblain'],['@type'=>'City','name'=>'Orvault'],['@type'=>'City','name'=>'Vertou']],'priceRange'=>'25 euros/jour'];
    echo '<script type="application/ld+json">'.wp_json_encode($lb,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE)."</script>\n";
    $faq=['@context'=>'https://schema.org','@type'=>'FAQPage','mainEntity'=>[['@type'=>'Question','name'=>'Combien coute la location ?','acceptedAnswer'=>['@type'=>'Answer','text'=>'25 euros/jour. Caution 100 euros.']],['@type'=>'Question','name'=>'Ou recuperer la machine ?','acceptedAnswer'=>['@type'=>'Answer','text'=>'Retrait sur Reze uniquement.']],['@type'=>'Question','name'=>'Est-ce facile ?','acceptedAnswer'=>['@type'=>'Answer','text'=>'Oui. Explications au retrait.']],['@type'=>'Question','name'=>'Temps de sechage ?','acceptedAnswer'=>['@type'=>'Answer','text'=>'Quelques heures.']],['@type'=>'Question','name'=>'Quelles zones ?','acceptedAnswer'=>['@type'=>'Answer','text'=>'Nantes, Reze, Saint-Herblain, Orvault, Vertou, Bouguenais.']]]];
    echo '<script type="application/ld+json">'.wp_json_encode($faq,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE)."</script>\n";
});

add_action('init',function(){remove_action('wp_head','wp_generator');remove_action('wp_head','wlwmanifest_link');remove_action('wp_head','rsd_link');remove_action('wp_head','wp_shortlink_wp_head');remove_action('wp_head','feed_links',2);remove_action('wp_head','feed_links_extra',3);});
add_filter('comments_open','__return_false',20,2);add_filter('pings_open','__return_false',20,2);
add_action('wp_enqueue_scripts',function(){wp_dequeue_style('wp-block-library');wp_dequeue_style('classic-theme-styles');wp_dequeue_style('global-styles');},100);
remove_action('wp_head','print_emoji_detection_script',7);remove_action('wp_print_styles','print_emoji_styles');
add_filter('excerpt_length',function(){return 25;},999);add_filter('excerpt_more',function(){return '...';});

function sn_nav(){get_template_part('template-parts/nav');}
function sn_ft(){get_template_part('template-parts/ft');}
function sn_form($x='hp'){set_query_var('sn_ctx',$x);get_template_part('template-parts/form');}
function sn_img($k){$m=['logo'=>'Karcher_Logo_2015.svg_.png','puzzi'=>'shampouineuse-karcher-pro-png.png','bed'=>'shampouineuse-nettoyage-lit-nantes.jpg','sofa'=>'shampouineuse-nettoyage-karcher-canape.jpg','close'=>'shampouineuse-location-nantes-reze.jpeg','dirty'=>'Canape-gris-avec-coussins-taches.png','clean'=>'Canape-gris-impeccablement-propre.png'];return isset($m[$k])?'https://shampouineuse-nantes.fr/wp-content/uploads/2026/02/'.$m[$k]:'';}

add_action('after_switch_theme','sn_seed');
function sn_seed(){
    $pp=[['Accueil','accueil','template-homepage.php'],['Location shampouineuse Nantes','location-shampouineuse-nantes','template-reservation.php'],['Nos conseils','nos-conseils','template-blog.php']];
    foreach($pp as $p){if(!get_page_by_path($p[1])){$id=wp_insert_post(['post_title'=>$p[0],'post_name'=>$p[1],'post_status'=>'publish','post_type'=>'page','post_author'=>1]);if($id)update_post_meta($id,'_wp_page_template',$p[2]);}}
    $hp=get_page_by_path('accueil');if($hp){update_option('show_on_front','page');update_option('page_on_front',$hp->ID);}
    $arts=[
        ['Nettoyer son canape a Nantes efficacement','nettoyer-canape-nantes',"<h2>Pourquoi nettoyer son canape en profondeur ?</h2><p>Un canape en tissu accumule poussieres, taches et odeurs au fil des mois. A Nantes, l'humidite accelere ce processus. Un simple aspirateur ne suffit plus. La solution la plus efficace reste le nettoyage par injection-extraction avec une shampouineuse professionnelle.</p><h2>La methode injection-extraction</h2><p>La shampouineuse Karcher Puzzi 8/1, disponible en <a href='/location-shampouineuse-nantes/'>location a Nantes pour 25 euros/jour</a>, projette un melange eau + detergent dans les fibres puis reaspire immediatement l'eau chargee de saletes. Le resultat est visible des le premier passage.</p><h2>Etapes du nettoyage</h2><p><strong>1. Aspirer</strong> le canape pour retirer miettes et poussieres.</p><p><strong>2. Preparer</strong> la solution dans le reservoir de la Puzzi.</p><p><strong>3. Injecter</strong> en passant le suceur sur toute la surface.</p><p><strong>4. Extraire</strong> en mode aspiration. Passages lents et reguliers.</p><p><strong>5. Laisser secher</strong> quelques heures avec bonne ventilation.</p><h2>Nos conseils</h2><p>Testez toujours sur une zone cachee. Faites des passages lents. Si le canape est tres sale, deux passages valent mieux qu'un. <a href='/location-shampouineuse-nantes/'>Reservez votre shampouineuse</a> et constatez la difference.</p>"],
        ['Prix location shampouineuse Nantes : guide complet','prix-location-shampouineuse-nantes',"<h2>Combien coute la location d'une shampouineuse a Nantes ?</h2><p>Notre service de <a href='/location-shampouineuse-nantes/'>location de shampouineuse a Nantes</a> est propose a 25 euros par jour. C'est le tarif le plus competitif de la region pour une machine professionnelle Karcher Puzzi 8/1.</p><h2>Ce qui est inclus</h2><p>La machine est livree prete a l'emploi. Vous recuperez la Puzzi 8/1 avec le suceur a main ergonomique et les explications de fonctionnement. Pas de frais caches.</p><h2>Conditions de location</h2><p>Caution de 100 euros + carte d'identite au retrait. Retrait uniquement sur Reze. Retour avant 20h. Plusieurs jours possibles. Service entre particuliers, plus de 300 clients satisfaits.</p><h2>Comparer avec les alternatives</h2><p>Un pressing facture entre 50 et 150 euros par canape. L'achat d'une shampouineuse grand public coute 200 a 400 euros pour un resultat inferieur. A 25 euros/jour avec une machine pro, la location est imbattable. <a href='/location-shampouineuse-nantes/'>Reservez maintenant</a>.</p>"],
        ['Nettoyage avant etat des lieux a Nantes','nettoyage-etat-des-lieux-nantes',"<h2>Recuperez votre caution</h2><p>Vous quittez votre logement a Nantes ? Des taches sur la moquette ou un canape defraichi peuvent justifier une retenue sur votre caution. La <a href='/location-shampouineuse-nantes/'>location d'une shampouineuse pro</a> est la solution la plus economique pour tout remettre a neuf.</p><h2>Que nettoyer avant l'etat des lieux ?</h2><p>Concentrez-vous sur les elements textiles visibles : moquettes, tapis, canape si le logement est meuble, rideaux epais. La Karcher Puzzi 8/1 gere toutes ces surfaces.</p><h2>Planning ideal</h2><p>Reservez la shampouineuse 2 a 3 jours avant l'etat des lieux pour laisser le temps au sechage. Commencez par les grandes surfaces puis les meubles. Prenez des photos avant/apres. Aerez bien.</p><h2>Un investissement rentable</h2><p>25 euros de location contre potentiellement plusieurs centaines d'euros de retenue sur caution. Le calcul est vite fait. <a href='/location-shampouineuse-nantes/'>Reservez votre shampouineuse</a>.</p>"],
        ['Shampouineuse ou nettoyage vapeur : que choisir ?','shampouineuse-ou-nettoyage-vapeur-nantes',"<h2>Deux methodes differentes</h2><p>La shampouineuse et le nettoyeur vapeur n'ont pas le meme fonctionnement. A Nantes, beaucoup hesitent entre les deux. Voici un comparatif clair.</p><h2>La shampouineuse (injection-extraction)</h2><p>La Karcher Puzzi 8/1, disponible en <a href='/location-shampouineuse-nantes/'>location a Nantes</a>, pulverise un melange eau + detergent dans les fibres puis aspire l'eau chargee de saletes. Elle extrait physiquement la salete.</p><h2>Le nettoyeur vapeur</h2><p>Projette de la vapeur sous pression. Efficace pour les surfaces dures (carrelage, vitres) mais moins adapte aux textiles epais. La vapeur repousse les saletes en profondeur au lieu de les extraire.</p><h2>Verdict pour les textiles</h2><p>Pour canapes, matelas et tapis, la shampouineuse l'emporte nettement. Elle penetre les fibres, dissout et extrait. Le nettoyeur vapeur est plus adapte aux surfaces dures. <a href='/location-shampouineuse-nantes/'>Louez une Puzzi 8/1 pour 25 euros/jour</a>.</p>"],
        ['Nettoyage canape apres taches animales a Nantes','nettoyage-canape-taches-animaux-nantes',"<h2>Animaux et canapes : un defi quotidien</h2><p>Chiens, chats, les animaux laissent des traces sur vos canapes : poils incrustes, odeurs persistantes, taches d'urine ou de boue. A Nantes, ou l'humidite amplifie les odeurs, un nettoyage en profondeur est indispensable.</p><h2>Pourquoi l'aspiration ne suffit pas</h2><p>Un aspirateur retire les poils en surface mais ne penetre pas les fibres. Les odeurs et les taches organiques restent. Seule la methode injection-extraction elimine saletes ET odeurs en profondeur.</p><h2>La Puzzi 8/1 contre les odeurs animales</h2><p>La <a href='/location-shampouineuse-nantes/'>Karcher Puzzi 8/1 en location a Nantes</a> injecte la solution nettoyante au coeur des fibres et reaspire toute la salete dissoute. Resultat : le tissu est assaini, les odeurs eliminees, le sechage rapide.</p><h2>Nos conseils</h2><p>Traitez les taches fraiches rapidement. Pour les taches anciennes, faites deux passages. Utilisez un detergent adapte aux textiles. Aerez bien apres nettoyage. <a href='/location-shampouineuse-nantes/'>Reservez votre shampouineuse pour 25 euros/jour</a>.</p>"]
    ];
    foreach($arts as $a){if(!get_page_by_path($a[1],OBJECT,'post'))wp_insert_post(['post_title'=>$a[0],'post_name'=>$a[1],'post_content'=>$a[2],'post_status'=>'publish','post_type'=>'post','post_author'=>1]);}
    flush_rewrite_rules();
}
